# Generated by Django 4.2.7 on 2023-12-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_view_by_alter_task_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='view_by',
            new_name='views_by',
        ),
    ]
